export const messageLanguages = ["en", "pl", "de", "es", "fr", "ja"] as const;
type Language = typeof messageLanguages[number];
type Translations = readonly [string, string, string, string, string, string];
export const messages = {
  scoreProfile: ["**{user}'s quiz card~ ♡**\nPoints: **{points}** · Answers: {answered} · Correct: {correct} ({accuracy}%)\nCurrent streak: **{streak}** · Best: **{best}**", "**Karta quizowa {user}~ ♡**\nPunkty: **{points}** · Odpowiedzi: {answered} · Poprawne: {correct} ({accuracy}%)\nObecna seria: **{streak}** · Najlepsza: **{best}**", "**Quizkarte von {user}~ ♡**\nPunkte: **{points}** · Antworten: {answered} · Richtig: {correct} ({accuracy}%)\nAktuelle Serie: **{streak}** · Beste: **{best}**", "**Ficha de {user}~ ♡**\nPuntos: **{points}** · Respuestas: {answered} · Correctas: {correct} ({accuracy}%)\nRacha actual: **{streak}** · Mejor: **{best}**", "**Carte de {user}~ ♡**\nPoints : **{points}** · Réponses : {answered} · Correctes : {correct} ({accuracy}%)\nSérie actuelle : **{streak}** · Meilleure : **{best}**", "**{user} のクイズカード~ ♡**\nポイント：**{points}** · 回答：{answered} · 正解：{correct}（{accuracy}%）\n現在の連続正解：**{streak}** · 最高：**{best}**"],
  scoreRules: ["Correct answer: easy 1 / medium 2 / hard 3 points. Scores settle after polls close and Discord finalizes votes. A wrong answer resets the streak; no vote does not. Only quizzes created after scoring was enabled count.", "Poprawna odpowiedź: easy 1 / medium 2 / hard 3 punkty. Naliczamy po zamknięciu ankiety i finalizacji głosów przez Discord. Błąd przerywa serię; brak głosu nie. Liczą się tylko quizy utworzone po włączeniu punktacji.", "Richtige Antwort: easy 1 / medium 2 / hard 3 Punkte. Wertung nach Umfrageende und finaler Auszählung durch Discord. Falsch setzt die Serie zurück; keine Stimme nicht. Nur neue Quizze zählen.", "Respuesta correcta: easy 1 / medium 2 / hard 3 puntos. Se cuentan al cerrar la encuesta y finalizar Discord los votos. Un error reinicia la racha; no votar no. Solo cuentan los nuevos quizzes.", "Bonne réponse : easy 1 / medium 2 / hard 3 points. Décompte après fermeture et finalisation par Discord. Une erreur remet la série à zéro ; l'absence de vote non. Seuls les nouveaux quiz comptent.", "正解：easy 1 / medium 2 / hard 3ポイント。投票終了後、Discordの最終集計後に加算。不正解で連続記録がリセットされ、未回答では変わりません。導入後の新しいクイズのみ対象です。"],
  leaderboardTitle: ["**Our little quiz stars~ (｡•̀ᴗ-)✧**", "**Nasze quizowe gwiazdki~ (｡•̀ᴗ-)✧**", "**Unsere kleinen Quizstars~ (｡•̀ᴗ-)✧**", "**Nuestras estrellas del quiz~ (｡•̀ᴗ-)✧**", "**Nos petites étoiles du quiz~ (｡•̀ᴗ-)✧**", "**クイズの小さなスターたち~ (｡•̀ᴗ-)✧**"],
  leaderboardRow: ["{rank}. {user} - **{points}** points · best streak {streak}", "{rank}. {user} - **{points}** punktów · najlepsza seria {streak}", "{rank}. {user} - **{points}** Punkte · beste Serie {streak}", "{rank}. {user} - **{points}** puntos · mejor racha {streak}", "{rank}. {user} - **{points}** points · meilleure série {streak}", "{rank}. {user} - **{points}**ポイント · 最高連続正解 {streak}"],
  scoreEmpty: ["No scores yet~ Vote in a new quiz and wait for it to close! ♡", "Jeszcze nie ma wyników~ Zagłosuj w nowym quizie i poczekaj na jego zamknięcie! ♡", "Noch keine Punkte~ Stimme in einem neuen Quiz ab und warte auf das Ende! ♡", "Aún no hay puntos~ ¡Vota en un quiz nuevo y espera su cierre! ♡", "Pas encore de scores~ Votez dans un nouveau quiz et attendez sa fermeture ! ♡", "まだ記録がないよ~ 新しいクイズで投票して終了を待ってね！ ♡"],
  forgetConfirm: ["To permanently delete your answers and score on this server, use `/score forget confirm:true`.", "Aby trwale usunąć swoje odpowiedzi i wynik na tym serwerze, użyj `/score forget confirm:true`.", "Um deine Antworten und Punkte auf diesem Server dauerhaft zu löschen, nutze `/score forget confirm:true`.", "Para borrar definitivamente tus respuestas y puntos de este servidor, usa `/score forget confirm:true`.", "Pour supprimer définitivement vos réponses et points sur ce serveur, utilisez `/score forget confirm:true`.", "このサーバーの回答とポイントを完全削除するには `/score forget confirm:true` を使ってね。"],
  scoreForgotten: ["Your stored answers and score on this server were deleted permanently. Pending polls and future votes can earn points again.", "Twoje zapisane odpowiedzi i wynik na tym serwerze zostały trwale usunięte. Oczekujące ankiety i przyszłe głosy mogą ponownie naliczyć punkty.", "Deine gespeicherten Antworten und Punkte auf diesem Server wurden dauerhaft gelöscht. Offene Umfragen und neue Stimmen können wieder Punkte ergeben.", "Tus respuestas y puntos guardados de este servidor se borraron definitivamente. Las encuestas pendientes y futuros votos pueden sumar puntos otra vez.", "Vos réponses et points enregistrés sur ce serveur ont été définitivement supprimés. Les sondages en attente et futurs votes peuvent à nouveau rapporter des points.", "このサーバーの保存済み回答とポイントを完全削除しました。未集計の投票や今後の回答では再びポイントが加算されることがあります。"],
  helpScore: ["profile, server leaderboard, or permanently delete your stored score with forget confirm:true", "profil, ranking serwera lub trwałe usunięcie własnego wyniku przez forget confirm:true", "Profil, Serverrangliste oder eigene Punkte mit forget confirm:true dauerhaft löschen", "perfil, clasificación o borrar tus puntos con forget confirm:true", "profil, classement ou supprimer vos points avec forget confirm:true", "プロフィール、ランキング、forget confirm:true で自分の記録を完全削除"],
  serverOnly: ["Use this command inside a server.", "Użyj tej komendy na serwerze.", "Nutze diesen Befehl auf einem Server.", "Usa este comando en un servidor.", "Utilisez cette commande dans un serveur.", "このコマンドはサーバーで使ってね。"],
  permission: ["You need Manage Server permission.", "Potrzebujesz uprawnienia Zarządzanie serwerem.", "Du brauchst die Berechtigung Server verwalten.", "Necesitas el permiso Gestionar servidor.", "La permission Gérer le serveur est nécessaire.", "サーバー管理の権限が必要です。"],
  channel: ["This channel cannot receive polls. Choose a text channel.", "Ten kanał nie może odbierać ankiet. Wybierz kanał tekstowy.", "Dieser Kanal kann keine Umfragen empfangen. Wähle einen Textkanal.", "Este canal no admite encuestas. Elige un canal de texto.", "Ce salon ne peut pas recevoir de sondages. Choisissez un salon textuel.", "このチャンネルでは投票できません。テキストチャンネルを選んでね。"],
  emptyTopics: ["No topics yet~ Create one with `/dilemma create`! ♡", "Nie mamy jeszcze tematów~ Dodaj pierwszy przez `/dilemma create`! ♡", "Noch keine Themen~ Erstelle eins mit `/dilemma create`! ♡", "Aún no hay temas~ ¡Crea uno con `/dilemma create`! ♡", "Pas encore de thèmes~ Créez-en un avec `/dilemma create` ! ♡", "まだテーマがないよ~ `/dilemma create` で作ってね！ ♡"],
  generating: ["Preparing your little quiz~ (｡•̀ᴗ-)✧ AI has up to {seconds} seconds per question. Difficulty: **{difficulty}**.", "Szykuję twój mały quiz~ (｡•̀ᴗ-)✧ AI ma do {seconds} sekund na pytanie. Poziom: **{difficulty}**.", "Dein kleiner Quiz wird vorbereitet~ (｡•̀ᴗ-)✧ KI: bis zu {seconds} Sekunden pro Frage. Schwierigkeit: **{difficulty}**.", "Preparando tu pequeño quiz~ (｡•̀ᴗ-)✧ La IA tiene hasta {seconds} segundos por pregunta. Nivel: **{difficulty}**.", "Je prépare votre petit quiz~ (｡•̀ᴗ-)✧ L'IA dispose de {seconds} secondes par question. Niveau : **{difficulty}**.", "小さなクイズを準備中~ (｡•̀ᴗ-)✧ AIの待ち時間は1問につき最大{seconds}秒。難易度：**{difficulty}**。"],
  randomDone: ["Your quiz is ready~ **{name}**, {count} answers! (≧◡≦) ♡", "Quiz gotowy~ **{name}**, {count} odpowiedzi! (≧◡≦) ♡", "Dein Quiz ist fertig~ **{name}**, {count} Antworten! (≧◡≦) ♡", "¡Tu quiz está listo~ **{name}**, {count} respuestas! (≧◡≦) ♡", "Votre quiz est prêt~ **{name}**, {count} réponses ! (≧◡≦) ♡", "クイズ完成~ **{name}**、選択肢は{count}個！ (≧◡≦) ♡"],
  timeout: ["AI did not respond in time. No new quiz was published for this question. Try again shortly.", "AI nie odpowiedziało na czas. Nie opublikowano nowego quizu dla tego pytania. Spróbuj ponownie za chwilę.", "Die KI hat nicht rechtzeitig geantwortet. Für diese Frage wurde kein neuer Quiz veröffentlicht. Versuche es gleich erneut.", "La IA no respondió a tiempo. No se publicó un nuevo quiz para esta pregunta. Inténtalo de nuevo en un momento.", "L'IA n'a pas répondu à temps. Aucun nouveau quiz n'a été publié pour cette question. Réessayez dans un instant.", "AIが時間内に応答しませんでした。この問題の新しいクイズは投稿されていません。少し待って再試行してね。"],
  quota: ["AI is temporarily unavailable due to provider limits or credits. Try again later.", "AI jest chwilowo niedostępne z powodu limitów lub salda dostawcy. Spróbuj później.", "Die KI ist wegen Anbieterlimits oder Guthaben vorübergehend nicht verfügbar. Versuche es später erneut.", "La IA no está disponible por límites o saldo del proveedor. Inténtalo más tarde.", "L'IA est indisponible à cause des limites ou du solde du fournisseur. Réessayez plus tard.", "提供元の制限または残高によりAIが利用できません。後で再試行してね。"],
  generationFailed: ["Could not finish the quiz. Check AI availability and the bot's Send Messages and Send Polls permissions.", "Nie udało się dokończyć quizu. Sprawdź dostępność AI oraz uprawnienia bota do wysyłania wiadomości i ankiet.", "Der Quiz konnte nicht abgeschlossen werden. Prüfe die KI sowie die Berechtigungen Nachrichten senden und Umfragen senden.", "No se pudo completar el quiz. Revisa la IA y los permisos del bot para enviar mensajes y encuestas.", "Le quiz n'a pas pu être terminé. Vérifiez l'IA et les permissions d'envoi de messages et de sondages du bot.", "クイズを完了できませんでした。AIの状態と、ボットのメッセージ送信・投票送信の権限を確認してね。"],
  missing: ["Topic **{name}** does not exist. Use `/dilemma list`.", "Temat **{name}** nie istnieje. Sprawdź `/dilemma list`.", "Thema **{name}** existiert nicht. Nutze `/dilemma list`.", "El tema **{name}** no existe. Usa `/dilemma list`.", "Le thème **{name}** n'existe pas. Utilisez `/dilemma list`.", "テーマ **{name}** がありません。`/dilemma list` を確認してね。"],
  exists: ["Topic **{name}** already exists. Choose another name.", "Temat **{name}** już istnieje. Wybierz inną nazwę.", "Thema **{name}** existiert bereits. Wähle einen anderen Namen.", "El tema **{name}** ya existe. Elige otro nombre.", "Le thème **{name}** existe déjà. Choisissez un autre nom.", "テーマ **{name}** は既にあります。別の名前を選んでね。"],
  renamed: ["A fresh name~ **{oldName}** is now **{name}**! ♡", "Nowe imię dla tematu~ **{oldName}** to teraz **{name}**! ♡", "Ein neuer Name~ **{oldName}** heißt jetzt **{name}**! ♡", "¡Nuevo nombre~ **{oldName}** ahora es **{name}**! ♡", "Un nouveau nom~ **{oldName}** devient **{name}** ! ♡", "新しい名前~ **{oldName}** が **{name}** になったよ！ ♡"],
  optionsInvalid: ["Provide 2-4 distinct answers separated by commas, each at most 55 characters.", "Podaj 2-4 różne odpowiedzi oddzielone przecinkami, każda do 55 znaków.", "Gib 2-4 verschiedene, durch Kommas getrennte Antworten an, jeweils höchstens 55 Zeichen.", "Indica 2-4 respuestas distintas separadas por comas, de hasta 55 caracteres cada una.", "Indiquez 2-4 réponses distinctes séparées par des virgules, chacune de 55 caractères maximum.", "カンマで区切った異なる回答を2-4個、各55文字以内で入力してね。"],
  optionsMismatch: ["With custom answers, option_count must match their count.", "Przy własnych odpowiedziach option_count musi odpowiadać ich liczbie.", "Bei eigenen Antworten muss option_count ihrer Anzahl entsprechen.", "Con respuestas propias, option_count debe coincidir con su cantidad.", "Avec des réponses personnalisées, option_count doit correspondre à leur nombre.", "回答を指定する場合、option_count は回答数と一致させてね。"],
  optionsMissing: ["Leave options empty and set option_count to 2-4 for AI answers.", "Zostaw options puste i ustaw option_count na 2-4 dla odpowiedzi AI.", "Lass options leer und setze option_count auf 2-4 für KI-Antworten.", "Deja options vacío y pon option_count en 2-4 para respuestas de IA.", "Laissez options vide et réglez option_count sur 2-4 pour des réponses générées par l'IA.", "AIの回答を使うには options を空にして option_count を2-4にしてね。"],
  saved: ["Topic **{name}** saved~ {count} answers, difficulty **{difficulty}**! (≧◡≦) ♡", "Temat **{name}** zapisany~ {count} odpowiedzi, poziom **{difficulty}**! (≧◡≦) ♡", "Thema **{name}** gespeichert~ {count} Antworten, Schwierigkeit **{difficulty}**! (≧◡≦) ♡", "¡Tema **{name}** guardado~ {count} respuestas, nivel **{difficulty}**! (≧◡≦) ♡", "Thème **{name}** enregistré~ {count} réponses, niveau **{difficulty}** ! (≧◡≦) ♡", "テーマ **{name}** を保存~ 回答{count}個、難易度 **{difficulty}**！ (≧◡≦) ♡"],
  deleted: ["Topic **{name}** removed~ Other topics are safe! ♡", "Temat **{name}** usunięty~ Pozostałe tematy są bez zmian! ♡", "Thema **{name}** entfernt~ Andere Themen bleiben unverändert! ♡", "¡Tema **{name}** eliminado~ Los demás siguen igual! ♡", "Thème **{name}** supprimé~ Les autres restent inchangés ! ♡", "テーマ **{name}** を削除~ 他のテーマはそのままだよ！ ♡"],
  runDone: ["Published {count} questions for **{name}**~ Time to vote! (｡•̀ᴗ-)✧", "Opublikowałam {count} pytań dla **{name}**~ Czas głosować! (｡•̀ᴗ-)✧", "{count} Fragen für **{name}** veröffentlicht~ Zeit zum Abstimmen! (｡•̀ᴗ-)✧", "¡{count} preguntas publicadas para **{name}**~ A votar! (｡•̀ᴗ-)✧", "{count} questions publiées pour **{name}**~ À vos votes ! (｡•̀ᴗ-)✧", "**{name}** に{count}問投稿したよ~ 投票しよう！ (｡•̀ᴗ-)✧"],
  settingsMissing: ["Provide at least one setting to change.", "Podaj przynajmniej jedno ustawienie do zmiany.", "Gib mindestens eine zu ändernde Einstellung an.", "Indica al menos un ajuste para cambiar.", "Indiquez au moins un réglage à modifier.", "変更する設定を1つ以上指定してね。"],
  timeInvalid: ["generation_time must use HH:mm, for example 18:30.", "generation_time musi mieć format HH:mm, na przykład 18:30.", "generation_time muss HH:mm verwenden, zum Beispiel 18:30.", "generation_time debe usar HH:mm, por ejemplo 18:30.", "generation_time doit utiliser HH:mm, par exemple 18:30.", "generation_time は HH:mm 形式で指定してね。例：18:30。"],
  summary: ["**{name}** - {state}, every {days} day(s), {count} question(s), {time}, **{difficulty}**, answers: {answers}", "**{name}** - {state}, co {days} dni, {count} pytań, {time}, **{difficulty}**, odpowiedzi: {answers}", "**{name}** - {state}, alle {days} Tage, {count} Fragen, {time}, **{difficulty}**, Antworten: {answers}", "**{name}** - {state}, cada {days} días, {count} preguntas, {time}, **{difficulty}**, respuestas: {answers}", "**{name}** - {state}, tous les {days} jours, {count} questions, {time}, **{difficulty}**, réponses : {answers}", "**{name}** - {state}、{days}日ごと、{count}問、{time}、**{difficulty}**、回答：{answers}"],
  enabled: ["enabled", "włączony", "aktiviert", "activado", "activé", "有効"],
  disabled: ["disabled", "wyłączony", "deaktiviert", "desactivado", "désactivé", "無効"],
  configured: ["Settings saved~ ♡\n{summary}", "Ustawienia zapisane~ ♡\n{summary}", "Einstellungen gespeichert~ ♡\n{summary}", "Ajustes guardados~ ♡\n{summary}", "Réglages enregistrés~ ♡\n{summary}", "設定を保存したよ~ ♡\n{summary}"],
  automatic: ["automatic", "automatycznie", "automatisch", "automático", "automatique", "自動"],
  aiAnswers: ["AI chooses {count}", "AI wybiera {count}", "KI wählt {count}", "la IA elige {count}", "l'IA choisit {count}", "AIが{count}個選択"],
  languageSet: ["I'll speak **{language}** with your server~ (≧◡≦) ♡", "Będę mówić z twoim serwerem w języku **{language}**~ (≧◡≦) ♡", "Ich spreche mit deinem Server jetzt **{language}**~ (≧◡≦) ♡", "¡Hablaré **{language}** con tu servidor~ (≧◡≦) ♡", "Je parlerai **{language}** avec votre serveur~ (≧◡≦) ♡", "このサーバーでは **{language}** で話すね~ (≧◡≦) ♡"],
  defaultsSet: ["Defaults saved~ Every {days} day(s), {count} questions, difficulty **{difficulty}**! ♡", "Domyślne ustawienia zapisane~ Co {days} dni, {count} pytań, poziom **{difficulty}**! ♡", "Standardwerte gespeichert~ Alle {days} Tage, {count} Fragen, Schwierigkeit **{difficulty}**! ♡", "¡Valores guardados~ Cada {days} días, {count} preguntas, nivel **{difficulty}**! ♡", "Valeurs enregistrées~ Tous les {days} jours, {count} questions, niveau **{difficulty}** ! ♡", "初期設定を保存~ {days}日ごと、{count}問、難易度 **{difficulty}**！ ♡"],
  notPoll: ["That message is not a poll.", "Ta wiadomość nie jest ankietą.", "Diese Nachricht ist keine Umfrage.", "Ese mensaje no es una encuesta.", "Ce message n'est pas un sondage.", "そのメッセージは投票ではありません。"],
  pollDone: ["Poll closed~ The results are ready! (｡•̀ᴗ-)✧", "Ankieta zamknięta~ Wyniki gotowe! (｡•̀ᴗ-)✧", "Umfrage geschlossen~ Die Ergebnisse sind da! (｡•̀ᴗ-)✧", "¡Encuesta cerrada~ Resultados listos! (｡•̀ᴗ-)✧", "Sondage fermé~ Les résultats sont prêts ! (｡•̀ᴗ-)✧", "投票を終了~ 結果が出たよ！ (｡•̀ᴗ-)✧"],
  pollFailed: ["Could not close this poll. Check message_id, the channel, whether it is already closed, and bot permissions.", "Nie udało się zamknąć ankiety. Sprawdź message_id, kanał, czy ankieta nie jest już zamknięta oraz uprawnienia bota.", "Umfrage konnte nicht geschlossen werden. Prüfe message_id, Kanal, Status und Bot-Berechtigungen.", "No se pudo cerrar la encuesta. Revisa message_id, el canal, su estado y los permisos del bot.", "Impossible de fermer le sondage. Vérifiez message_id, le salon, son état et les permissions du bot.", "投票を終了できませんでした。message_id、チャンネル、終了済みかどうか、ボット権限を確認してね。"],
  error: ["Something went wrong. Try again later. If questions were already published, check the channel before retrying.", "Coś poszło nie tak. Spróbuj później. Jeśli pytania już się pojawiły, sprawdź kanał przed ponowną próbą.", "Etwas ist schiefgelaufen. Versuche es später erneut. Prüfe vor einem neuen Versuch, ob bereits Fragen veröffentlicht wurden.", "Algo salió mal. Inténtalo más tarde. Antes de repetir, comprueba si ya se publicaron preguntas.", "Une erreur est survenue. Réessayez plus tard. Vérifiez d'abord si des questions ont déjà été publiées.", "エラーが発生しました。後で再試行してね。再試行前に問題が既に投稿されていないか確認してください。"],
  ping: ["Pong~ Dilemma is here for you! (≧◡≦) ♡", "Pong~ Dilemma jest tutaj dla ciebie! (≧◡≦) ♡", "Pong~ Dilemma ist für dich da! (≧◡≦) ♡", "¡Pong~ Dilemma está aquí para ti! (≧◡≦) ♡", "Pong~ Dilemma est là pour vous ! (≧◡≦) ♡", "Pong~ Dilemmaはここにいるよ！ (≧◡≦) ♡"],
  easy: ["Easy", "Łatwy", "Leicht", "Fácil", "Facile", "やさしい"],
  medium: ["Medium", "Średni", "Mittel", "Medio", "Moyen", "ふつう"],
  hard: ["Hard", "Trudny", "Schwer", "Difícil", "Difficile", "むずかしい"],
  difficulty: ["Difficulty: {difficulty}", "Poziom: {difficulty}", "Schwierigkeit: {difficulty}", "Nivel: {difficulty}", "Niveau : {difficulty}", "難易度：{difficulty}"],
  helpIntro: ["Your little command guide~ (｡•̀ᴗ-)✧", "Twój mały przewodnik po komendach~ (｡•̀ᴗ-)✧", "Dein kleiner Befehlsführer~ (｡•̀ᴗ-)✧", "Tu pequeña guía de comandos~ (｡•̀ᴗ-)✧", "Votre petit guide des commandes~ (｡•̀ᴗ-)✧", "小さなコマンドガイド~ (｡•̀ᴗ-)✧"],
  helpCreate: ["create a topic; optional difficulty", "dodaj temat; opcjonalny difficulty", "Thema erstellen; difficulty optional", "crear tema; difficulty opcional", "créer un thème ; difficulty facultatif", "テーマ作成、difficulty は任意"],
  helpConfigure: ["set interval, question count, time and difficulty", "ustaw odstęp, liczbę pytań, godzinę i difficulty", "Intervall, Fragenzahl, Uhrzeit und difficulty einstellen", "ajustar intervalo, preguntas, hora y difficulty", "régler intervalle, nombre de questions, heure et difficulty", "間隔、問題数、時刻、difficulty を設定"],
  helpToggle: ["control automatic generation", "steruj automatycznym generowaniem", "automatische Generierung steuern", "controlar generación automática", "gérer la génération automatique", "自動生成を切り替え"],
  helpRun: ["publish questions with the topic's saved difficulty", "opublikuj pytania z zapisanym poziomem tematu", "Fragen mit gespeicherter Schwierigkeit veröffentlichen", "publicar preguntas con el nivel guardado", "publier les questions au niveau enregistré", "保存した難易度で問題を投稿"],
  helpRandom: ["random quiz; option_count:2-4, optional difficulty:easy/medium/hard", "losowy quiz; option_count:2-4, opcjonalny difficulty:easy/medium/hard", "Zufallsquiz; option_count:2-4, difficulty:easy/medium/hard optional", "quiz aleatorio; option_count:2-4, difficulty:easy/medium/hard opcional", "quiz aléatoire ; option_count:2-4, difficulty:easy/medium/hard facultatif", "ランダムクイズ、option_count:2-4、difficulty:easy/medium/hard は任意"],
  helpList: ["list topics and difficulty", "wyświetl tematy i poziomy", "Themen und Schwierigkeit anzeigen", "mostrar temas y niveles", "afficher thèmes et niveaux", "テーマと難易度を表示"],
  helpManage: ["rename or remove a topic", "zmień nazwę lub usuń temat", "Thema umbenennen oder entfernen", "renombrar o eliminar un tema", "renommer ou supprimer un thème", "テーマ名を変更・削除"],
  helpSettings: ["server language and defaults, including difficulty", "język serwera i domyślne ustawienia, także difficulty", "Serversprache und Standardwerte einschließlich difficulty", "idioma y valores predeterminados, incluido difficulty", "langue et valeurs par défaut, dont difficulty", "サーバー言語と difficulty を含む初期設定"],
  helpPoll: ["close a poll and publish results", "zamknij ankietę i opublikuj wyniki", "Umfrage schließen und Ergebnisse veröffentlichen", "cerrar encuesta y publicar resultados", "fermer le sondage et publier les résultats", "投票を終了し結果を投稿"],
  partial: ["Earlier questions in this run may already be published. Check the channel before retrying.", "Wcześniejsze pytania z tego uruchomienia mogły już zostać opublikowane. Sprawdź kanał przed ponowną próbą.", "Frühere Fragen dieses Durchlaufs könnten bereits veröffentlicht sein. Prüfe den Kanal vor einem neuen Versuch.", "Puede que ya se hayan publicado preguntas de esta ejecución. Revisa el canal antes de repetir.", "Des questions de cette exécution ont peut-être déjà été publiées. Vérifiez le salon avant de réessayer.", "この実行の前の問題は既に投稿されている可能性があります。再試行前にチャンネルを確認してね。"]
} as const satisfies Record<string, Translations>;
export type MessageKey = keyof typeof messages;
export function normalizeLanguage(language: string): Language {
  const base = language.toLowerCase().split("-")[0];
  return messageLanguages.includes(base as Language) ? base as Language : "en";
}
export function message(language: string, key: MessageKey, values: Record<string, string | number> = {}): string {
  const text = messages[key][messageLanguages.indexOf(normalizeLanguage(language))];
  return text.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
}
